spring:
  datasource:
    username: "postgres"
    password: "qwerty"
    url: "jdbc:postgresql://localhost/test"
    driver-class: "org.postgresql.Driver"
  jpa:
    show-sql: false
    open-in-view: true




